### ISSUE TITLE
CLIC-8 Inventory Statistics

### ISSUE THREAD

**Issue by kevinmurphy5** [whagan/custom_addons#29]
As the business owner, I want to know what products I should restock, so I don't restock items I'm losing money on or restock items that I still have plenty of.

TASK DESCRIPTION
By the end of the iteration, the ClickIt Restock Report should be listed under the "My Reports" sub-menu in the Custom Reports module. The restock report will require its own models/tables.

HOW TO EVALUATE

In Odoo, go to **Settings** → **Technical** (navbar) → **Models** (under Database Structure). Search custom_reports. One of the models belonging to the custom_reports module should be the Restock Report module and have similar fields as mentioned above.

Also, go to **Custom Reports** -> **Custom Reports** (navbar) ->Restock Report. Create an Inventory Statistics Report. After saving, this data should be saved in the database in tables Restock and Restock Report.

**Comment by chang3d** [comment]
Since there already is an inventory report from the inventory itself, this report really is the restock report. The task description has been adjusted accordingly. The restock report will require the tables in the inventory (stock) and the purchasing (purchase) modules on top of the base modules.
