### ISSUE TITLE
CLIC-36 Fix Boolean Datetime Issues

### ISSUE THREAD

**Issue by chang3d** [whagan/custom_addons#36]
For some strange reasons, a null datetime in a saved Odoo model will be treated as a Boolean by python. This may make future editing of that field problematic, as some models have functions tied to that field and it thinks it could be a Boolean that's being compared to a datetime.

Potential fixes are to set default datetimes or make them required fields.

**Comment by whagan** [comment]
![image](https://user-images.githubusercontent.com/13141382/98029959-e872a880-1dd5-11eb-8c9f-ce6d4197332e.png)

**Comment by whagan** [comment]
Taken from hr_attendance model:

![image](https://user-images.githubusercontent.com/13141382/98030038-04764a00-1dd6-11eb-877b-586eee9cfa1a.png)

**Comment by whagan** [comment]
Might need to import exceptions and _ from odoo and **require** start_date and end_date fields (as @chang3d  mentioned in our meeting).
